Tmux better layout switching, automatic tmux sessions

diff --git a/sh/.sources/tmux b/sh/.sources/tmux
--- a/sh/.sources/tmux
+++ b/sh/.sources/tmux
@@ -63,5 +63,37 @@ function tmux-distribute-top() {
   done
 }
 
+# tx-update-main-pane-dims: 
+#   Recalculates 'main-pane-width' and 'main-pane-height' using preset
+#   percentages of the client width and height. 
+function tx-update-main-pane-dims() {
+  [ -z "$TMUX" ] && { echo "ERROR: this command must be run from tmux" >&2;
+  return; 1; }
+
+  local width height
+  while getopts 'w:h:' opt; do
+    case "$opt" in
+      w) width=$OPTARG ;;
+      h) height=$OPTARG ;;
+    esac
+  done
+
+  if [[ $width -le 0 ]] || [[ $width -gt 100 ]] ||\
+     [[ $height -le 0 ]] || [[ $height -gt 100 ]]; then
+    echo 'ERROR: width and height must be percentage values between 1 and 100' >&2;
+    return 1
+  fi
+
+  local cwidth=$(tmux display-message -pF '#{client_width}')
+  local cheight=$(tmux display-message -pF '#{client_height}')
+
+  local pwidth=$(expr $cwidth \* $width \/ 100)
+  local pheight=$(expr $cheight \* $height \/ 100)
+
+  tmux set-window-option main-pane-width $pwidth
+  tmux set-window-option main-pane-height $pheight
+  tmux select-layout
+}
+
 alias ts='tmux-switch-session'
 alias tw='tmux-switch-window'
